language: node_js
cache:
  directories:
    - node_modules
script:
  - yarn build
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: ./build
