blank_issues_enabled: false
contact_links:
  - name: Discord
    about: This is the main channel for external communication and the quickest way to get help.
    url: https://discord.gg/5Ann5C3
  - name: Stack Overflow
    about: If you’ve got a broad question that doesn’t necessarily relate to the project, you can ask a question on Stack Overflow.
    url: https://stackoverflow.com/questions/tagged/rmuif
